adf <- read.csv('Flournoy.new.csv')

#assume v is thet voxel-wise estimate of the self-other contrast
adf$v <- rnorm(dim(adf)[1], 0, 1)

#widen the data for lavaan
library(tidyr)
adf_w <- adf[, grep('age', names(adf), invert = T)] %>% 
  gather(variable, value, pds, v) %>%
  unite(var_time, variable, time) %>%
  spread(var_time, value)

head(adf_w)

require(lavaan)

cor_lgc_model <- '
#centered at wave 2, time unit = years
v_i =~ 1*v_0 + 1*v_1 + 1*v_2
v_s =~ -3*v_0 + 0*v_1 + 3*v_2
pds_i =~ 1*pds_0 + pds*v_1 + pds*v_2
pds_s =~ -3*pds_0 + 0*pds_1 + 3*pds_2

#correlations explicitly coded, but would be generated by default
v_i ~~ v_s + pds_i + pds_s
v_s ~~ pds_i + pds_s
pds_i ~~ pds_s
'

cor_lgc_fit <- lavaan::growth(cor_lgc_model, data = adf_w)

summary(cor_lgc_fit)

#many options in lavaan for extracting information from the model
#see http://lavaan.ugent.be/tutorial/inspect.html
param_ests <- parameterEstimates(cor_lgc_fit)
std_param_ests <- standardizedsolution(cor_lgc_fit,type="std.all")
fit_measures <- fitMeasures(cor_lgc_fit)

#the user will almost certainly want the values for the intercepts and covariances of the latent growth parameters
latent_int <- param_ests[param_ests$lhs %in% c('v_i', 'v_s', 'pds_i', 'pds_s') & 
                           param_ests$op %in% c('~1'),]
latent_varcov <- param_ests[param_ests$lhs %in% c('v_i', 'v_s', 'pds_i', 'pds_s') & 
                           param_ests$op %in% c('~~'),]
