#!/bin/bash
# copy files to local context and build
rm -rf npoint npointrun neuropointillist
cp ../../npoint .
cp ../../npointrun .
cp -r ../../neuropointillist .
docker build -t neuropointillist-nextflow .

